# Generated by Django 5.0.1 on 2025-06-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('Baby', 'Baby'), ('Kid', 'Kid'), ('Nail Enhancement', 'Nail'), ('Manicure', 'Mani'), ('Eyelash Extensions', 'Eyelash'), ('Pedicure', 'Pedi'), ('Wax', 'Wax'), ('YFix', 'Yfix')], default='Nail Enhancement', help_text='Choose one of the categories.', max_length=20),
        ),
    ]
