# Generated by Django 5.0.1 on 2025-06-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachvisit',
            name='isPaid',
            field=models.BooleanField(default=False, help_text='Has the client paid for this visit?'),
        ),
    ]
